# permissions for end users to edit k8soperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: k8soperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8soperator
    app.kubernetes.io/part-of: k8soperator
    app.kubernetes.io/managed-by: kustomize
  name: k8soperator-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - k8soperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - k8soperators/status
  verbs:
  - get
